// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLXOFIkp-B5MtjOicKwVW3NYTPT4iAS8',
    appId: '1:929923332493:android:3f14d9b13ab43bbed9a5c4',
    messagingSenderId: '929923332493',
    projectId: 'expense-tracker-bb203',
    storageBucket: 'expense-tracker-bb203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxRQnk7-9zXG3_a9egDwCWjcZY0AUWRbk',
    appId: '1:929923332493:ios:ba526b1a8c9c9794d9a5c4',
    messagingSenderId: '929923332493',
    projectId: 'expense-tracker-bb203',
    storageBucket: 'expense-tracker-bb203.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFgSb_2Tui-jknK0wsASbkexT7q3d6p8',
    appId: '1:929923332493:web:32b11e1bd67d1051d9a5c4',
    messagingSenderId: '929923332493',
    projectId: 'expense-tracker-bb203',
    authDomain: 'expense-tracker-bb203.firebaseapp.com',
    storageBucket: 'expense-tracker-bb203.firebasestorage.app',
    measurementId: 'G-1H494LRGFJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxRQnk7-9zXG3_a9egDwCWjcZY0AUWRbk',
    appId: '1:929923332493:ios:ba526b1a8c9c9794d9a5c4',
    messagingSenderId: '929923332493',
    projectId: 'expense-tracker-bb203',
    storageBucket: 'expense-tracker-bb203.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOFgSb_2Tui-jknK0wsASbkexT7q3d6p8',
    appId: '1:929923332493:web:65942c934fd34d8cd9a5c4',
    messagingSenderId: '929923332493',
    projectId: 'expense-tracker-bb203',
    authDomain: 'expense-tracker-bb203.firebaseapp.com',
    storageBucket: 'expense-tracker-bb203.firebasestorage.app',
    measurementId: 'G-4CM5WZ6EB4',
  );

}